services:
  - type: web
    name: sentiment-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run src/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
